const ERRORS = {
  '404': {
    num: '404',
    warnNum: false,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 30% 80%, #001a05 0%, #010c01 70%)',
    bgOpacity: 0.8,
    lines: [
      { text: "what you're looking for left.", cls: 'accent' },
      { text: 'like everyone else.',           cls: 'accent' },
      { text: '' },
      { text: 'signal        : absent',        cls: 'muted' },
      { text: 'last seen     : a while ago',   cls: 'muted' },
      { text: 'forwarding    : none',          cls: 'muted' },
    ],
  },

  '500': {
    num: '500',
    warnNum: true,
    glitch: true,
    caOn: true,
    bg: 'radial-gradient(ellipse at 60% 30%, #1a0008 0%, #010c01 65%)',
    bgOpacity: 0.85,
    lines: [
      { text: 'everything broke.',             cls: 'warn' },
      { text: 'including you.',                cls: 'warn' },
      { text: '' },
      { text: 'origin        : unclear',       cls: 'muted' },
      { text: 'recovery      : not scheduled', cls: 'muted' },
      { text: 'recommendation: sit with it',   cls: 'muted' },
    ],
  },

  '403': {
    num: '403',
    warnNum: true,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 50% 20%, #0a0010 0%, #010c01 65%)',
    bgOpacity: 0.7,
    lines: [
      { text: 'denied.',                          cls: 'warn' },
      { text: 'even to the parts of yourself',   cls: 'accent' },
      { text: 'you needed most.',                cls: 'accent' },
      { text: '' },
      { text: 'permissions   : revoked',          cls: 'muted' },
      { text: 'reason        : undisclosed',      cls: 'muted' },
      { text: 'you were never on the list.',      cls: 'muted' },
    ],
  },

  '410': {
    num: '410',
    warnNum: false,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 20% 70%, #001508 0%, #010c01 70%)',
    bgOpacity: 0.6,
    lines: [
      { text: 'gone.',                            cls: 'mid' },
      { text: 'not temporarily.',                cls: 'mid' },
      { text: '' },
      { text: 'cached version: also gone',       cls: 'muted' },
      { text: 'backup        : never made',      cls: 'muted' },
      { text: "some things don't leave traces.", cls: 'muted' },
    ],
  },

  '418': {
    num: '418',
    warnNum: false,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 70% 60%, #001a10 0%, #010c01 65%)',
    bgOpacity: 0.6,
    lines: [
      { text: "i'm a teapot.",                        cls: 'good' },
      { text: "you're something harder to classify.", cls: 'good' },
      { text: '' },
      { text: 'beverage      : unspecified',          cls: 'muted' },
      { text: 'brewing       : existential residue',  cls: 'muted' },
      { text: 'temperature   : wrong, probably',      cls: 'muted' },
    ],
  },

  '401': {
    num: '401',
    warnNum: true,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 40% 50%, #120005 0%, #010c01 65%)',
    bgOpacity: 0.7,
    lines: [
      { text: 'unauthorized.',                   cls: 'warn' },
      { text: '' },
      { text: "you don't have the credentials", cls: 'accent' },
      { text: 'for this version of okay.',      cls: 'accent' },
      { text: '' },
      { text: "try again. (you won't.)",        cls: 'dim' },
    ],
  },

  '503': {
    num: '503',
    warnNum: false,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 55% 45%, #001208 0%, #010c01 65%)',
    bgOpacity: 0.6,
    lines: [
      { text: 'temporarily unavailable.',       cls: 'mid' },
      { text: '' },
      { text: "redefining 'temporarily'...",    cls: 'muted' },
      { text: 'estimated return: pending hope', cls: 'muted' },
      { text: 'hope          : also 503',       cls: 'dim' },
    ],
  },

  '408': {
    num: '408',
    warnNum: false,
    glitch: false,
    caOn: false,
    bg: 'radial-gradient(ellipse at 30% 40%, #001005 0%, #010c01 65%)',
    bgOpacity: 0.55,
    lines: [
      { text: 'request timeout.',                      cls: 'mid' },
      { text: '' },
      { text: 'you waited too long to ask.',           cls: 'muted' },
      { text: 'the window closed.',                    cls: 'muted' },
      { text: 'there are always windows that close.', cls: 'dim' },
    ],
  },
};

const HIDDEN = {
  'love':          ['command not recognized.', '', '(checked twice.)'],
  'sudo fix-life': ['permission denied.', '', 'nice try.'],
  'sudo fix-me':   ['permission denied.', '', "even root can't do that."],
  'exit':          ['you cannot leave that easily.', '', 'none of us can.'],
  'quit':          ['still here.'],
  'reboot': [
    'initiating reboot...',
    'saving state...',
    'state: unsaveable.',
    '',
    'reboot cancelled.',
    'same session continues.',
  ],
  'rm -rf /': [
    'nice try.',
    '',
    'you cannot delete yourself that easily.',
    'trust me, people have tried.',
  ],
  'man feelings': ['no manual entry for feelings.', '', 'shocking, right?'],
  'ssh home':     ['connecting to home...', 'connection refused.', '', "it's complicated."],
  'curl hope': [
    'curl: (7) failed to connect: connection refused',
    '',
    'try again later.',
    "or don't. hope is weird like that.",
  ],
  'ping self': [
    '64 bytes from self: seq=1 time=...',
    '64 bytes from self: seq=2 time=...',
    '64 bytes from self: seq=3 time=...',
    '',
    'response detected.',
    'you are still there.',
  ],
  'whoami': [
    'running identity check...',
    '',
    'result: inconclusive.',
    '',
    "you are here. that's enough for now.",
  ],
  'ls': [
    'available feelings/',
    '  grief/',
    '  denial/',
    '  brief-okay/',
    '  almost-fine/',
    '  unreturned-messages/',
    '  [hidden]/   (access: unknown)',
    '',
    'total: more than expected',
  ],
  'status': [
    'emotional_os v0.3.1',
    '────────────────────────────────',
    'uptime        : too long',
    'stability     : fluctuating',
    'memory usage  : significant',
    'errors logged : yes',
    'recovery mode : not initiated',
    '────────────────────────────────',
    'system is running.',
    "whether that's good is unclear.",
  ],
  'help': [
    'known codes:  404  500  403  410  418  401  503  408',
    '',
    'commands:',
    "  clear       wipe the session",
    "  status      system self-assessment",
    "  ls          list available feelings",
    "  whoami      identity check",
    "  ping self   see if you're still there",
    '',
    "there are commands that aren't listed.",
  ],
  'clear': '__CLEAR__',
};
